__author__ = 'perun'

import core.networks as nw
import core.test as test


class Data:
    def __init__(self):
        """
        Method initialize interests matrix for 3 class of flow, list of creted by user networks and index to handle
        operations on networks.

        """
        self.interest_matrix_voice = []
        self.interest_matrix_video = []
        self.interest_matrix_be = []
        self.networks = []
        self.index = 0

#Methods connected with displaying Data class
    def process_data(self):

        self.split_matrix()

        for nets in self.networks:
            nets.reset_resources()

        for nets in self.networks:
            if 'GSM' in nets.name:
                nets.set_intensity_voice_out(self.networks)

        for nets in self.networks:
            if 'GSM' in nets.name:
                nets.input_resources()
                nets.output_resources()

    def show_data(self):
        for x in self.networks:
            print("+++++++++++++++++")
            for y in (x.__dict__.keys()):
                print("{} = {}".format(y, x.__dict__[y]))
            print("+++++++++++++++++")

    def use_test_values(self):
        self.interest_matrix_voice = test.interest_matrix
        for tmp in test.test_networks():
            self.networks.append(tmp)
            self.index = test.index

#Methods connected with processing Data class
    def create_circuit_network(self, intensity=0, loss=0):

        """
        Method is adding new circuit network, with values set by user, to the row of networks
        :param intensity: Intensity generated by network
        :param loss: loss probability
        """
        self.networks.append(nw.Circuit(intensity, self.index, loss))
        self.index += 1

    def create_package_network(self, intensity=0):

        """
        Method is adding new package network, with values set by user, to the row of networks
        :param intensity: Intensity generated by network
        """
        self.networks.append(nw.Package(intensity, self.index))
        self.index += 1

    def delete_network(self, n=None):

        """
        Method is deleting selected network from the row of created networks. It also removes the row from an interest
        matrix belonging to deleted network. Finally it reorganise index of existing networks and reprocess data.
        :param n: Index of network to delete
        """
        self.networks.pop(n)
        self.index -= 1

        for x in range(self.index+1):
            self.networks[x].set_index(x)
            self.interest_matrix_voice[x].pop(n)
        self.interest_matrix_voice.pop(n)
        self.process_data()

    def create_interest_matrix(self):
        """
        Creating the interest matrix based on the number of networks
        """
        self.interest_matrix_voice = []
        for ly in range(self.index+1):
            self.interest_matrix_voice.append(
                [float(input('x[{}][{}] = '.format(ly, lx))) for lx in range(self.index+1)])

    def split_matrix(self):
        """
        Method which partial interest matrix into row to every network
        :return: set the value of interest_row_voice in instance of the network class
        """
        for temp in self.networks:
            temp.interest_row = self.interest_matrix_voice[temp.index]

    def change_single_value_matrix(self, row, col):
        self.interest_matrix_voice[row][col] = input('Podaj nowa wartosc: ')


if __name__ == '__main__':
    pass